#!/usr/bin/env bash

cmd=$1

case ${cmd} in
    togglepause)
        if [[ $(rmpc status | jq -r ".state") == "Stop" ]]; then
            rmpc play
        fi
        rmpc togglepause
        ;;
    next)
        rmpc next
        ;;
    prev)
        rmpc prev
        ;;
    down)
        rmpc volume -5
        volume_icon=""
        ;;
    up)
        rmpc volume +5
        volume_icon=""
        ;;
    *)
        echo "Usage: $0 [togglepause|next|prev|down|up]"
        exit 1
        ;;
esac

status_state=$(rmpc status | jq -r ".state")
case ${status_state} in
    Stop)
        state_icon=""
        ;;
    Pause)
        state_icon=""
        ;;
    Play)
        state_icon=""
        ;;
esac

case ${cmd} in
    togglepause|next|prev)
        song_title=$(rmpc song | jq -r ".metadata.title")
        song_artist=$(rmpc song | jq -r ".metadata.artist")
        song_album=$(rmpc song | jq -r ".metadata.album")
        song_albumartist=$(rmpc song | jq -r ".metadata.albumartist")
        NOTIFY_ID=2727
        notify-send -t 2000 -h "string:x-canonical-private-synchronous:rmpc-song" \
            "${state_icon}  rmpc" " 󰲸\t${song_title} - ${song_artist}\n 󰀥\t${song_album} - ${song_albumartist}"
        ;;
    down|up)
        status_volume=$(rmpc status | jq ".volume")
        NOTIFY_ID=3939
        notify-send -t 1000 -h int:value:$status_volume -h "string:x-dunst-stack-tag:vol" \
            "${state_icon}  rmpc" "${volume_icon}   Volume: ${status_volume}%" -i audio-volume-medium
        ;;
esac

