#!/usr/bin/env bash

if [[ -z "$TMUX" ]]; then
    ID="$(tmux ls 2>/dev/null | grep -vm1 attached | cut -d: -f1)"  # get the id of a detached session
    if [[ -z "$ID" ]]; then  # if not available create a new one
        tmux new-session -s "tmux-$(date '+%Y/%m/%d-%H/%M/%S')"
    else
        tmux attach-session -t "$ID"  # if available attach to it
    fi
fi
